// Generated by https://quicktype.io

export interface CatalogueHolidays {
  _id: string;
  name: string;
  country: string;
  isActive: boolean;
  id_tm: number;
  __v: number;
  createdAt: string;
  updatedAt: string;
}
// Generated by https://quicktype.io

export interface CurrentHolidays {
  _id: string;
  date: string;
  holidays: Holiday[];
}

export interface Holiday {
  name: string;
}
