// Generated by https://quicktype.io

export interface PreauthorizationHttp {
  _id: string;
  id_employee: string;
  name_responsible: string;
  email_responsible: string;
  project_role: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}
