// Generated by https://quicktype.io

export interface PreauthorizationHttp {
  _id: string;
  id_employee: number;
  name: string;
  email: string;
  project_role: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}
